/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lightwarrior (https://sketchfab.com/lightwarrior)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pirate-hunter-d8c7df95b9614390bc4d907172cd3e9d
title: Pirate Hunter
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/carrier.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1} position={[0, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Tex_0020_0_dds}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/carrier.gltf");
