/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: akselmot (https://sketchfab.com/akselmot)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/desert-planet-colony-day-1-b9fe9a69da52411e9472cb2a020933a8
title: Desert planet colony. Day 1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/colony.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[7.75, 1.95, 0]}>
            <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
            <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
          </group>
          <group position={[3.65, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
          </group>
          <group position={[-0.93, 1.98, 0]}>
            <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
            <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
          </group>
          <group position={[-0.84, 3.16, 0]} scale={[0.94, 0.94, 0.94]}>
            <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
            <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
          </group>
          <group position={[3.65, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
          </group>
          <group position={[3.65, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
          </group>
          <group position={[3.66, 0.44, 0]}>
            <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
          </group>
          <group position={[3.66, 0.45, 0]}>
            <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
            <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
          </group>
          <group position={[7.75, 1.95, 0]}>
            <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
          </group>
          <group position={[5.27, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} />
          </group>
          <group position={[9.86, 1.95, 0]}>
            <mesh geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} />
          </group>
          <group position={[5.65, 1.95, 0]}>
            <mesh geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} />
          </group>
          <group position={[6.78, 1.95, 0]}>
            <mesh geometry={nodes.mesh_16.geometry} material={nodes.mesh_16.material} />
          </group>
          <group position={[8.74, 1.95, 0]}>
            <mesh geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} />
          </group>
          <group position={[6.22, 0.45, 0.07]}>
            <mesh geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} />
            <mesh geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} />
          </group>
          <group position={[6.13, 0.07, 0.07]}>
            <mesh geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} />
          </group>
          <group position={[6.17, 0.44, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} />
          </group>
          <group position={[9.31, 0.45, 0.07]}>
            <mesh geometry={nodes.mesh_22.geometry} material={nodes.mesh_22.material} />
            <mesh geometry={nodes.mesh_23.geometry} material={nodes.mesh_23.material} />
          </group>
          <group position={[9.22, 0.07, 0.07]}>
            <mesh geometry={nodes.mesh_24.geometry} material={nodes.mesh_24.material} />
          </group>
          <group position={[9.26, 0.44, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_25.geometry} material={nodes.mesh_25.material} />
          </group>
          <group position={[7.22, 1.95, 0]}>
            <mesh geometry={nodes.mesh_26.geometry} material={nodes.mesh_26.material} />
          </group>
          <group position={[8.39, 1.95, 0]}>
            <mesh geometry={nodes.mesh_27.geometry} material={nodes.mesh_27.material} />
          </group>
          <group position={[7.93, 1.81, 0]}>
            <mesh geometry={nodes.mesh_28.geometry} material={nodes.mesh_28.material} />
          </group>
          <group position={[7.75, 1.95, -0.01]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.mesh_29.geometry} material={nodes.mesh_29.material} />
          </group>
          <group position={[12.64, 1.9, 0]} rotation={[Math.PI, 0, Math.PI / 2]}>
            <mesh geometry={nodes.mesh_30.geometry} material={nodes.mesh_30.material} />
            <mesh geometry={nodes.mesh_31.geometry} material={nodes.mesh_31.material} />
          </group>
          <group position={[10.26, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_32.geometry} material={nodes.mesh_32.material} />
          </group>
          <group position={[7.45, 3.17, 0]}>
            <mesh geometry={nodes.mesh_33.geometry} material={nodes.mesh_33.material} />
          </group>
          <group position={[8.13, 3.17, -0.18]} scale={[0.27, 0.05, 0.28]}>
            <mesh geometry={nodes.mesh_34.geometry} material={nodes.mesh_34.material} />
          </group>
          <group position={[7.41, 3.84, 0]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.mesh_35.geometry} material={nodes.mesh_35.material} />
          </group>
          <group position={[7.89, 3.2, 0.14]} scale={[0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_36.geometry} material={nodes.mesh_36.material} />
          </group>
          <group position={[7.89, 3.2, -0.49]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_37.geometry} material={nodes.mesh_37.material} />
          </group>
          <group position={[7.97, 3.22, -0.35]} scale={[0.04, 0.01, 0.04]}>
            <mesh geometry={nodes.mesh_38.geometry} material={nodes.mesh_38.material} />
          </group>
          <group position={[8.29, 3.22, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.mesh_39.geometry} material={nodes.mesh_39.material} />
          </group>
          <group position={[10.9, 0.44, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_40.geometry} material={nodes.mesh_40.material} />
          </group>
          <group position={[10.87, -0.79, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_41.geometry} material={nodes.mesh_41.material} />
          </group>
          <group position={[-0.84, 3.12, 0]} scale={[0.94, 0.94, 0.94]}>
            <mesh geometry={nodes.mesh_42.geometry} material={nodes.mesh_42.material} />
          </group>
          <group position={[-0.93, 2.14, 0]} scale={[1.02, 1.02, 1.02]}>
            <mesh geometry={nodes.mesh_43.geometry} material={nodes.mesh_43.material} />
          </group>
          <group position={[-0.93, 1.98, 0]}>
            <mesh geometry={nodes.mesh_44.geometry} material={nodes.mesh_44.material} />
          </group>
          <group position={[-0.93, 1.98, 0]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_45.geometry} material={nodes.mesh_45.material} />
          </group>
          <group position={[2.04, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_46.geometry} material={nodes.mesh_46.material} />
          </group>
          <group position={[-0.94, 1.9, -4.55]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_47.geometry} material={nodes.mesh_47.material} />
          </group>
          <group position={[-0.94, 1.9, -4.55]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_48.geometry} material={nodes.mesh_48.material} />
          </group>
          <group position={[-0.94, 1.9, -4.55]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_49.geometry} material={nodes.mesh_49.material} />
          </group>
          <group position={[-0.94, 0.44, -4.54]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_50.geometry} material={nodes.mesh_50.material} />
          </group>
          <group position={[-0.94, 0.45, -4.55]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_51.geometry} material={nodes.mesh_51.material} />
            <mesh geometry={nodes.mesh_52.geometry} material={nodes.mesh_52.material} />
          </group>
          <group position={[-0.94, 1.9, -2.94]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_53.geometry} material={nodes.mesh_53.material} />
          </group>
          <group position={[-0.94, 1.9, -6.16]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_54.geometry} material={nodes.mesh_54.material} />
          </group>
          <group position={[-0.94, 1.9, 4.58]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_55.geometry} material={nodes.mesh_55.material} />
          </group>
          <group position={[-0.94, 1.9, 4.58]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_56.geometry} material={nodes.mesh_56.material} />
          </group>
          <group position={[-0.94, 1.9, 4.58]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_57.geometry} material={nodes.mesh_57.material} />
          </group>
          <group position={[-0.94, 0.44, 4.58]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_58.geometry} material={nodes.mesh_58.material} />
          </group>
          <group position={[-0.94, 0.45, 4.58]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_59.geometry} material={nodes.mesh_59.material} />
            <mesh geometry={nodes.mesh_60.geometry} material={nodes.mesh_60.material} />
          </group>
          <group position={[-0.94, 1.9, 6.19]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_61.geometry} material={nodes.mesh_61.material} />
          </group>
          <group position={[-0.94, 1.9, 2.97]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_62.geometry} material={nodes.mesh_62.material} />
          </group>
          <group position={[-0.93, 1.98, -9.14]}>
            <mesh geometry={nodes.mesh_63.geometry} material={nodes.mesh_63.material} />
            <mesh geometry={nodes.mesh_64.geometry} material={nodes.mesh_64.material} />
          </group>
          <group position={[-0.84, 3.16, -9.14]} scale={[0.94, 0.94, 0.94]}>
            <mesh geometry={nodes.mesh_65.geometry} material={nodes.mesh_65.material} />
            <mesh geometry={nodes.mesh_66.geometry} material={nodes.mesh_66.material} />
          </group>
          <group position={[-0.84, 3.12, -9.14]} scale={[0.94, 0.94, 0.94]}>
            <mesh geometry={nodes.mesh_67.geometry} material={nodes.mesh_67.material} />
          </group>
          <group position={[-0.93, 2.14, -9.14]} scale={[1.02, 1.02, 1.02]}>
            <mesh geometry={nodes.mesh_68.geometry} material={nodes.mesh_68.material} />
          </group>
          <group position={[-0.93, 1.98, -9.14]}>
            <mesh geometry={nodes.mesh_69.geometry} material={nodes.mesh_69.material} />
          </group>
          <group position={[-0.93, 1.98, -9.14]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_70.geometry} material={nodes.mesh_70.material} />
          </group>
          <group position={[3.65, 1.9, -9.12]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_71.geometry} material={nodes.mesh_71.material} />
          </group>
          <group position={[3.65, 1.9, -9.12]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_72.geometry} material={nodes.mesh_72.material} />
          </group>
          <group position={[3.65, 1.9, -9.12]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_73.geometry} material={nodes.mesh_73.material} />
          </group>
          <group position={[3.66, 0.44, -9.12]}>
            <mesh geometry={nodes.mesh_74.geometry} material={nodes.mesh_74.material} />
          </group>
          <group position={[3.66, 0.45, -9.12]}>
            <mesh geometry={nodes.mesh_75.geometry} material={nodes.mesh_75.material} />
            <mesh geometry={nodes.mesh_76.geometry} material={nodes.mesh_76.material} />
          </group>
          <group position={[2.04, 1.9, -9.12]} rotation={[0, 0, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_77.geometry} material={nodes.mesh_77.material} />
          </group>
          <group position={[-5.48, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_78.geometry} material={nodes.mesh_78.material} />
          </group>
          <group position={[-5.48, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_79.geometry} material={nodes.mesh_79.material} />
          </group>
          <group position={[-5.48, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_80.geometry} material={nodes.mesh_80.material} />
          </group>
          <group position={[-5.48, 0.44, 0]}>
            <mesh geometry={nodes.mesh_81.geometry} material={nodes.mesh_81.material} />
          </group>
          <group position={[-5.48, 0.45, 0]}>
            <mesh geometry={nodes.mesh_82.geometry} material={nodes.mesh_82.material} />
            <mesh geometry={nodes.mesh_83.geometry} material={nodes.mesh_83.material} />
          </group>
          <group position={[-3.87, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_84.geometry} material={nodes.mesh_84.material} />
          </group>
          <group position={[-7.09, 1.9, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_85.geometry} material={nodes.mesh_85.material} />
          </group>
          <group position={[-5.48, 1.9, -9.1]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_86.geometry} material={nodes.mesh_86.material} />
          </group>
          <group position={[-5.48, 1.9, -9.1]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_87.geometry} material={nodes.mesh_87.material} />
          </group>
          <group position={[-5.48, 1.9, -9.1]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_88.geometry} material={nodes.mesh_88.material} />
          </group>
          <group position={[-5.48, 0.44, -9.1]}>
            <mesh geometry={nodes.mesh_89.geometry} material={nodes.mesh_89.material} />
          </group>
          <group position={[-5.48, 0.45, -9.1]}>
            <mesh geometry={nodes.mesh_90.geometry} material={nodes.mesh_90.material} />
            <mesh geometry={nodes.mesh_91.geometry} material={nodes.mesh_91.material} />
          </group>
          <group position={[-3.87, 1.9, -9.1]} rotation={[0, 0, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_92.geometry} material={nodes.mesh_92.material} />
          </group>
          <group position={[-7.09, 1.9, -9.1]} rotation={[0, 0, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_93.geometry} material={nodes.mesh_93.material} />
          </group>
          <group position={[-0.94, 1.9, -13.69]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_94.geometry} material={nodes.mesh_94.material} />
          </group>
          <group position={[-0.94, 1.9, -13.69]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_95.geometry} material={nodes.mesh_95.material} />
          </group>
          <group position={[-0.94, 1.9, -13.69]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_96.geometry} material={nodes.mesh_96.material} />
          </group>
          <group position={[-0.94, 0.44, -13.69]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_97.geometry} material={nodes.mesh_97.material} />
          </group>
          <group position={[-0.94, 0.45, -13.69]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_98.geometry} material={nodes.mesh_98.material} />
            <mesh geometry={nodes.mesh_99.geometry} material={nodes.mesh_99.material} />
          </group>
          <group position={[-0.94, 1.9, -12.08]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_100.geometry} material={nodes.mesh_100.material} />
          </group>
          <group position={[-0.94, 1.9, -15.31]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_101.geometry} material={nodes.mesh_101.material} />
          </group>
          <group position={[-9.61, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_102.geometry} material={nodes.mesh_102.material} />
            <mesh geometry={nodes.mesh_103.geometry} material={nodes.mesh_103.material} />
          </group>
          <group position={[-9.61, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_104.geometry} material={nodes.mesh_104.material} />
          </group>
          <group position={[-11.71, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_105.geometry} material={nodes.mesh_105.material} />
          </group>
          <group position={[-7.51, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_106.geometry} material={nodes.mesh_106.material} />
          </group>
          <group position={[-8.63, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_107.geometry} material={nodes.mesh_107.material} />
          </group>
          <group position={[-10.6, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_108.geometry} material={nodes.mesh_108.material} />
          </group>
          <group position={[-8.08, 0.45, -0.06]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_109.geometry} material={nodes.mesh_109.material} />
            <mesh geometry={nodes.mesh_110.geometry} material={nodes.mesh_110.material} />
          </group>
          <group position={[-7.99, 0.07, -0.06]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_111.geometry} material={nodes.mesh_111.material} />
          </group>
          <group position={[-8.03, 0.44, 0.01]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_112.geometry} material={nodes.mesh_112.material} />
          </group>
          <group position={[-11.16, 0.45, -0.06]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_113.geometry} material={nodes.mesh_113.material} />
            <mesh geometry={nodes.mesh_114.geometry} material={nodes.mesh_114.material} />
          </group>
          <group position={[-11.08, 0.07, -0.06]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_115.geometry} material={nodes.mesh_115.material} />
          </group>
          <group position={[-11.12, 0.44, 0.01]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_116.geometry} material={nodes.mesh_116.material} />
          </group>
          <group position={[-9.08, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_117.geometry} material={nodes.mesh_117.material} />
          </group>
          <group position={[-10.25, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_118.geometry} material={nodes.mesh_118.material} />
          </group>
          <group position={[-9.79, 1.81, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_119.geometry} material={nodes.mesh_119.material} />
          </group>
          <group position={[-9.61, 1.95, 0.02]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.mesh_120.geometry} material={nodes.mesh_120.material} />
          </group>
          <group position={[-14.5, 1.9, 0.02]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_121.geometry} material={nodes.mesh_121.material} />
            <mesh geometry={nodes.mesh_122.geometry} material={nodes.mesh_122.material} />
          </group>
          <group position={[-12.12, 1.9, 0.02]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_123.geometry} material={nodes.mesh_123.material} />
          </group>
          <group position={[-9.31, 3.17, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_124.geometry} material={nodes.mesh_124.material} />
          </group>
          <group position={[-9.98, 3.17, 0.19]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.27, 0.05, 0.28]}>
            <mesh geometry={nodes.mesh_125.geometry} material={nodes.mesh_125.material} />
          </group>
          <group position={[-9.27, 3.84, 0.02]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.mesh_126.geometry} material={nodes.mesh_126.material} />
          </group>
          <group position={[-9.75, 3.2, -0.12]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_127.geometry} material={nodes.mesh_127.material} />
          </group>
          <group position={[-9.75, 3.2, 0.51]} rotation={[0, 0, 0]} scale={[-0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_128.geometry} material={nodes.mesh_128.material} />
          </group>
          <group position={[-9.83, 3.22, 0.37]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.04, 0.01, 0.04]}>
            <mesh geometry={nodes.mesh_129.geometry} material={nodes.mesh_129.material} />
          </group>
          <group position={[-10.15, 3.22, 0.02]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.mesh_130.geometry} material={nodes.mesh_130.material} />
          </group>
          <group position={[-12.75, 0.44, 0.02]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_131.geometry} material={nodes.mesh_131.material} />
          </group>
          <group position={[-12.73, -0.79, 0.02]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_132.geometry} material={nodes.mesh_132.material} />
          </group>
          <group position={[-9.61, 1.95, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_133.geometry} material={nodes.mesh_133.material} />
            <mesh geometry={nodes.mesh_134.geometry} material={nodes.mesh_134.material} />
          </group>
          <group position={[-9.61, 1.95, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_135.geometry} material={nodes.mesh_135.material} />
          </group>
          <group position={[-11.71, 1.95, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_136.geometry} material={nodes.mesh_136.material} />
          </group>
          <group position={[-7.51, 1.95, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_137.geometry} material={nodes.mesh_137.material} />
          </group>
          <group position={[-8.63, 1.95, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_138.geometry} material={nodes.mesh_138.material} />
          </group>
          <group position={[-10.6, 1.95, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_139.geometry} material={nodes.mesh_139.material} />
          </group>
          <group position={[-8.08, 0.45, -9.17]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_140.geometry} material={nodes.mesh_140.material} />
            <mesh geometry={nodes.mesh_141.geometry} material={nodes.mesh_141.material} />
          </group>
          <group position={[-7.99, 0.07, -9.17]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_142.geometry} material={nodes.mesh_142.material} />
          </group>
          <group position={[-8.03, 0.44, -9.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_143.geometry} material={nodes.mesh_143.material} />
          </group>
          <group position={[-11.16, 0.45, -9.17]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_144.geometry} material={nodes.mesh_144.material} />
            <mesh geometry={nodes.mesh_145.geometry} material={nodes.mesh_145.material} />
          </group>
          <group position={[-11.08, 0.07, -9.17]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_146.geometry} material={nodes.mesh_146.material} />
          </group>
          <group position={[-11.12, 0.44, -9.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_147.geometry} material={nodes.mesh_147.material} />
          </group>
          <group position={[-9.08, 1.95, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_148.geometry} material={nodes.mesh_148.material} />
          </group>
          <group position={[-10.25, 1.95, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_149.geometry} material={nodes.mesh_149.material} />
          </group>
          <group position={[-9.79, 1.81, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_150.geometry} material={nodes.mesh_150.material} />
          </group>
          <group position={[-9.61, 1.95, -9.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.mesh_151.geometry} material={nodes.mesh_151.material} />
          </group>
          <group position={[-14.5, 1.9, -9.1]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.mesh_152.geometry} material={nodes.mesh_152.material} />
            <mesh geometry={nodes.mesh_153.geometry} material={nodes.mesh_153.material} />
          </group>
          <group position={[-12.12, 1.9, -9.1]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_154.geometry} material={nodes.mesh_154.material} />
          </group>
          <group position={[-9.31, 3.17, -9.1]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_155.geometry} material={nodes.mesh_155.material} />
          </group>
          <group position={[-9.98, 3.17, -8.92]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.27, 0.05, 0.28]}>
            <mesh geometry={nodes.mesh_156.geometry} material={nodes.mesh_156.material} />
          </group>
          <group position={[-9.27, 3.84, -9.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.mesh_157.geometry} material={nodes.mesh_157.material} />
          </group>
          <group position={[-9.75, 3.2, -9.24]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_158.geometry} material={nodes.mesh_158.material} />
          </group>
          <group position={[-9.75, 3.2, -8.61]} rotation={[0, 0, 0]} scale={[-0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_159.geometry} material={nodes.mesh_159.material} />
          </group>
          <group position={[-9.83, 3.22, -8.75]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.04, 0.01, 0.04]}>
            <mesh geometry={nodes.mesh_160.geometry} material={nodes.mesh_160.material} />
          </group>
          <group position={[-10.15, 3.22, -9.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.mesh_161.geometry} material={nodes.mesh_161.material} />
          </group>
          <group position={[-12.75, 0.44, -9.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_162.geometry} material={nodes.mesh_162.material} />
          </group>
          <group position={[-12.73, -0.79, -9.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_163.geometry} material={nodes.mesh_163.material} />
          </group>
          <group position={[-0.95, 1.95, 8.67]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_164.geometry} material={nodes.mesh_164.material} />
            <mesh geometry={nodes.mesh_165.geometry} material={nodes.mesh_165.material} />
          </group>
          <group position={[-0.95, 1.95, 8.67]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_166.geometry} material={nodes.mesh_166.material} />
          </group>
          <group position={[-0.95, 1.95, 10.78]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_167.geometry} material={nodes.mesh_167.material} />
          </group>
          <group position={[-0.95, 1.95, 6.57]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_168.geometry} material={nodes.mesh_168.material} />
          </group>
          <group position={[-0.95, 1.95, 7.7]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_169.geometry} material={nodes.mesh_169.material} />
          </group>
          <group position={[-0.95, 1.95, 9.66]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_170.geometry} material={nodes.mesh_170.material} />
          </group>
          <group position={[-1.02, 0.45, 7.14]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_171.geometry} material={nodes.mesh_171.material} />
            <mesh geometry={nodes.mesh_172.geometry} material={nodes.mesh_172.material} />
          </group>
          <group position={[-1.02, 0.07, 7.05]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_173.geometry} material={nodes.mesh_173.material} />
          </group>
          <group position={[-0.95, 0.44, 7.09]} rotation={[0, -Math.PI / 2, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_174.geometry} material={nodes.mesh_174.material} />
          </group>
          <group position={[-1.02, 0.45, 10.23]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_175.geometry} material={nodes.mesh_175.material} />
            <mesh geometry={nodes.mesh_176.geometry} material={nodes.mesh_176.material} />
          </group>
          <group position={[-1.02, 0.07, 10.14]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_177.geometry} material={nodes.mesh_177.material} />
          </group>
          <group position={[-0.95, 0.44, 10.18]} rotation={[0, -Math.PI / 2, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_178.geometry} material={nodes.mesh_178.material} />
          </group>
          <group position={[-0.95, 1.95, 8.14]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_179.geometry} material={nodes.mesh_179.material} />
          </group>
          <group position={[-0.95, 1.95, 9.31]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_180.geometry} material={nodes.mesh_180.material} />
          </group>
          <group position={[-0.95, 1.81, 8.85]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_181.geometry} material={nodes.mesh_181.material} />
          </group>
          <group position={[-0.94, 1.95, 8.67]} rotation={[0, -Math.PI / 2, 0]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.mesh_182.geometry} material={nodes.mesh_182.material} />
          </group>
          <group position={[-0.95, 3.17, 8.37]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_183.geometry} material={nodes.mesh_183.material} />
          </group>
          <group position={[-0.77, 3.17, 9.05]} rotation={[0, -Math.PI / 2, 0]} scale={[0.27, 0.05, 0.28]}>
            <mesh geometry={nodes.mesh_184.geometry} material={nodes.mesh_184.material} />
          </group>
          <group position={[-0.95, 3.84, 8.33]} rotation={[0, -Math.PI / 2, 0]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.mesh_185.geometry} material={nodes.mesh_185.material} />
          </group>
          <group position={[-1.08, 3.2, 8.81]} rotation={[0, -Math.PI / 2, 0]} scale={[0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_186.geometry} material={nodes.mesh_186.material} />
          </group>
          <group position={[-0.46, 3.2, 8.81]} rotation={[0, Math.PI / 2, 0]} scale={[-0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_187.geometry} material={nodes.mesh_187.material} />
          </group>
          <group position={[-0.6, 3.22, 8.89]} rotation={[0, -Math.PI / 2, 0]} scale={[0.04, 0.01, 0.04]}>
            <mesh geometry={nodes.mesh_188.geometry} material={nodes.mesh_188.material} />
          </group>
          <group position={[-0.95, 3.22, 9.21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.mesh_189.geometry} material={nodes.mesh_189.material} />
          </group>
          <group position={[-0.95, 0.44, 11.82]} rotation={[0, -Math.PI / 2, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_190.geometry} material={nodes.mesh_190.material} />
          </group>
          <group position={[-0.95, -0.79, 11.79]} rotation={[0, -Math.PI / 2, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_191.geometry} material={nodes.mesh_191.material} />
          </group>
          <group position={[-0.94, 1.9, 12.79]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_192.geometry} material={nodes.mesh_192.material} />
          </group>
          <group position={[-0.94, 1.9, 12.79]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_193.geometry} material={nodes.mesh_193.material} />
          </group>
          <group position={[-0.94, 1.9, 12.79]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_194.geometry} material={nodes.mesh_194.material} />
          </group>
          <group position={[-0.94, 0.44, 12.79]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_195.geometry} material={nodes.mesh_195.material} />
          </group>
          <group position={[-0.94, 0.45, 12.79]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_196.geometry} material={nodes.mesh_196.material} />
            <mesh geometry={nodes.mesh_197.geometry} material={nodes.mesh_197.material} />
          </group>
          <group position={[-0.94, 1.9, 11.18]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_198.geometry} material={nodes.mesh_198.material} />
          </group>
          <group position={[-0.94, 1.9, 14.43]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_199.geometry} material={nodes.mesh_199.material} />
          </group>
          <group position={[-0.95, 1.95, 16.91]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_200.geometry} material={nodes.mesh_200.material} />
            <mesh geometry={nodes.mesh_201.geometry} material={nodes.mesh_201.material} />
          </group>
          <group position={[-0.95, 1.95, 16.91]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_202.geometry} material={nodes.mesh_202.material} />
          </group>
          <group position={[-0.95, 1.95, 19.01]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_203.geometry} material={nodes.mesh_203.material} />
          </group>
          <group position={[-0.95, 1.95, 14.81]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_204.geometry} material={nodes.mesh_204.material} />
          </group>
          <group position={[-0.95, 1.95, 15.93]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_205.geometry} material={nodes.mesh_205.material} />
          </group>
          <group position={[-0.95, 1.95, 17.89]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_206.geometry} material={nodes.mesh_206.material} />
          </group>
          <group position={[-1.02, 0.45, 15.37]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_207.geometry} material={nodes.mesh_207.material} />
            <mesh geometry={nodes.mesh_208.geometry} material={nodes.mesh_208.material} />
          </group>
          <group position={[-1.02, 0.07, 15.29]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_209.geometry} material={nodes.mesh_209.material} />
          </group>
          <group position={[-0.95, 0.44, 15.33]} rotation={[0, -Math.PI / 2, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_210.geometry} material={nodes.mesh_210.material} />
          </group>
          <group position={[-1.02, 0.45, 18.46]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_211.geometry} material={nodes.mesh_211.material} />
            <mesh geometry={nodes.mesh_212.geometry} material={nodes.mesh_212.material} />
          </group>
          <group position={[-1.02, 0.07, 18.38]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_213.geometry} material={nodes.mesh_213.material} />
          </group>
          <group position={[-0.95, 0.44, 18.42]} rotation={[0, -Math.PI / 2, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_214.geometry} material={nodes.mesh_214.material} />
          </group>
          <group position={[-0.95, 1.95, 16.38]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_215.geometry} material={nodes.mesh_215.material} />
          </group>
          <group position={[-0.95, 1.95, 17.54]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_216.geometry} material={nodes.mesh_216.material} />
          </group>
          <group position={[-0.95, 1.81, 17.09]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_217.geometry} material={nodes.mesh_217.material} />
          </group>
          <group position={[-0.94, 1.95, 16.91]} rotation={[0, -Math.PI / 2, 0]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.mesh_218.geometry} material={nodes.mesh_218.material} />
          </group>
          <group position={[-0.95, 3.17, 16.61]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.mesh_219.geometry} material={nodes.mesh_219.material} />
          </group>
          <group position={[-0.77, 3.17, 17.28]} rotation={[0, -Math.PI / 2, 0]} scale={[0.27, 0.05, 0.28]}>
            <mesh geometry={nodes.mesh_220.geometry} material={nodes.mesh_220.material} />
          </group>
          <group position={[-0.95, 3.84, 16.57]} rotation={[0, -Math.PI / 2, 0]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.mesh_221.geometry} material={nodes.mesh_221.material} />
          </group>
          <group position={[-1.08, 3.2, 17.05]} rotation={[0, -Math.PI / 2, 0]} scale={[0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_222.geometry} material={nodes.mesh_222.material} />
          </group>
          <group position={[-0.46, 3.2, 17.05]} rotation={[0, Math.PI / 2, 0]} scale={[-0.01, 0.01, 0.05]}>
            <mesh geometry={nodes.mesh_223.geometry} material={nodes.mesh_223.material} />
          </group>
          <group position={[-0.6, 3.22, 17.13]} rotation={[0, -Math.PI / 2, 0]} scale={[0.04, 0.01, 0.04]}>
            <mesh geometry={nodes.mesh_224.geometry} material={nodes.mesh_224.material} />
          </group>
          <group position={[-0.95, 3.22, 17.45]} rotation={[0, -Math.PI / 2, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.mesh_225.geometry} material={nodes.mesh_225.material} />
          </group>
          <group position={[-0.95, 0.44, 20.05]} rotation={[0, -Math.PI / 2, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_226.geometry} material={nodes.mesh_226.material} />
          </group>
          <group position={[-0.95, -0.79, 20.03]} rotation={[0, -Math.PI / 2, 0]} scale={[0.42, 0.42, 0.42]}>
            <mesh geometry={nodes.mesh_227.geometry} material={nodes.mesh_227.material} />
          </group>
          <group position={[-0.98, 1.9, 21.66]} rotation={[0, 1.55, -1.57]}>
            <mesh geometry={nodes.mesh_228.geometry} material={nodes.mesh_228.material} />
            <mesh geometry={nodes.mesh_229.geometry} material={nodes.mesh_229.material} />
          </group>
          <group position={[-0.94, 1.9, 19.29]} rotation={[Math.PI, -1.55, 1.57]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.mesh_230.geometry} material={nodes.mesh_230.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/colony.gltf')
