/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: iKuroiNeko (https://sketchfab.com/iKuroiNeko)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/37f059291bbe40aa89e63d788df3fe1f
title: Little Planet
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/planet.gltf");

  useFrame(({ mouse }) => {
    group.current.rotation.y += 0.005;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2}>
        <group position={[2.33, 2.58, 1.53]}>
          <mesh
            geometry={nodes.Cube_0.geometry}
            material={nodes.Cube_0.material}
          />
        </group>
        <group position={[-0.46, 7.19, 6.08]} scale={[1.38, 1.38, 0.96]}>
          <mesh
            geometry={nodes.Icosphere001_0.geometry}
            material={nodes.Icosphere001_0.material}
          />
        </group>
        <group position={[-1.37, 4.72, 7.88]} scale={[3.39, 2.17, 1.93]}>
          <mesh
            geometry={nodes.Icosphere002_0.geometry}
            material={nodes.Icosphere002_0.material}
          />
        </group>
        <group
          position={[-0.19, 2.71, 9.49]}
          rotation={[0, 0, 0.98]}
          scale={[2.49, 2.49, 2.49]}
        >
          <mesh
            geometry={nodes.Icosphere003_0.geometry}
            material={nodes.Icosphere003_0.material}
          />
        </group>
        <group
          position={[-0.03, 0.52, 7.81]}
          rotation={[0, 0, 2.86]}
          scale={[1.12, 1.12, 0.81]}
        >
          <mesh
            geometry={nodes.Icosphere004_0.geometry}
            material={nodes.Icosphere004_0.material}
          />
        </group>
        <group
          position={[-0.38, 5.61, 9.92]}
          rotation={[0, 0, 2.86]}
          scale={[1.12, 1.12, 0.81]}
        >
          <mesh
            geometry={nodes.Icosphere005_0.geometry}
            material={nodes.Icosphere005_0.material}
          />
        </group>
        <group position={[-0.02, -3.02, 2.67]} rotation={[0.54, 0, 0]}>
          <mesh
            geometry={nodes.Icosphere006_0.geometry}
            material={nodes.Icosphere006_0.material}
          />
        </group>
        <group
          position={[-0.01, -1.76, 2.59]}
          rotation={[0.19, 0, 0]}
          scale={[0.57, 0.57, 0.35]}
        >
          <mesh
            geometry={nodes.Icosphere007_0.geometry}
            material={nodes.Icosphere007_0.material}
          />
        </group>
        <group position={[-0.52, -0.47, -5.23]} scale={[8.09, 8.09, 8.09]}>
          <mesh
            geometry={nodes.Icosphere_0.geometry}
            material={materials.Grass}
          />
          <mesh
            geometry={nodes.Icosphere_1.geometry}
            material={materials.Water}
          />
        </group>
        <group position={[42.5, -0.27, 17.01]} rotation={[0, 0.66, 0]} />
        <group
          position={[6, -4.76, 1.94]}
          rotation={[0.33, 0.49, 0.92]}
          scale={[1.45, 1.45, 1.45]}
        >
          <mesh
            geometry={nodes.Icosphere008_0.geometry}
            material={nodes.Icosphere008_0.material}
          />
          <mesh
            geometry={nodes.Icosphere008_1.geometry}
            material={nodes.Icosphere008_1.material}
          />
        </group>
        <group
          position={[7.38, -1.78, 0.25]}
          rotation={[0.04, 0.89, 1.49]}
          scale={[0.89, 0.89, 0.89]}
        >
          <mesh
            geometry={nodes.Icosphere009_0.geometry}
            material={nodes.Icosphere009_0.material}
          />
          <mesh
            geometry={nodes.Icosphere009_1.geometry}
            material={nodes.Icosphere009_1.material}
          />
        </group>
        <group
          position={[-8.02, -3.02, -7.74]}
          rotation={[2.17, -0.89, 2.3]}
          scale={[1.51, 1.51, 0.92]}
        >
          <mesh
            geometry={nodes.Icosphere010_0.geometry}
            material={nodes.Icosphere010_0.material}
          />
        </group>
        <group
          position={[-8.96, -3.02, -8.69]}
          rotation={[2.17, -0.89, 2.3]}
          scale={[0.62, 0.62, 0.37]}
        >
          <mesh
            geometry={nodes.Icosphere011_0.geometry}
            material={nodes.Icosphere011_0.material}
          />
        </group>
        <group
          position={[-6.12, -1.89, -13.85]}
          rotation={[2.99, -0.28, -3]}
          scale={[1.45, 1.45, 1.45]}
        >
          <mesh
            geometry={nodes.Icosphere012_0.geometry}
            material={nodes.Icosphere012_0.material}
          />
          <mesh
            geometry={nodes.Icosphere012_1.geometry}
            material={nodes.Icosphere012_1.material}
          />
        </group>
        <group
          position={[2.58, -0.52, -13.56]}
          rotation={[-2.96, 0.06, -3]}
          scale={[0.73, 0.73, 0.73]}
        >
          <mesh
            geometry={nodes.Icosphere013_0.geometry}
            material={nodes.Icosphere013_0.material}
          />
          <mesh
            geometry={nodes.Icosphere013_1.geometry}
            material={nodes.Icosphere013_1.material}
          />
        </group>
        <group
          position={[0.34, -3.58, -13.73]}
          rotation={[2.81, 0.21, -3.11]}
          scale={[0.73, 0.73, 0.73]}
        >
          <mesh
            geometry={nodes.Icosphere014_0.geometry}
            material={nodes.Icosphere014_0.material}
          />
          <mesh
            geometry={nodes.Icosphere014_1.geometry}
            material={nodes.Icosphere014_1.material}
          />
        </group>
        <group
          position={[-2.61, 5.87, -10.8]}
          rotation={[0.56, 0.26, -0.16]}
          scale={[1.51, 1.51, 0.92]}
        >
          <mesh
            geometry={nodes.Icosphere015_0.geometry}
            material={nodes.Icosphere015_0.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/planet.gltf");
