/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Pavel Korobka (https://sketchfab.com/PavelKorobka)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hw5-xyz-school-detailed-draft-model-1-1128b6a7a8c74c998cb34defb1dce0cc
title: [HW5 XYZ School] Detailed Draft. Model 1.
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/rover.gltf");

  useFrame(({ mouse }) => {
    group.current.position.x = -mouse.x * 100.5;
    group.current.position.y = -mouse.y * 100.5;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[224.41, 94.87, 400.02]}
            rotation={[-1.23, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[0, 0, 0.16]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder173_White_metal_d1_0.geometry}
                material={nodes.Cylinder173_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder173_White_metal_d2_0.geometry}
                material={nodes.Cylinder173_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <group
                position={[0, 0, 0]}
                rotation={[0, 0, -0.16]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder176_White_metal_d2_0.geometry}
                  material={nodes.Cylinder176_White_metal_d2_0.material}
                />
                <mesh
                  geometry={nodes.Cylinder176_White_metal_d1_0.geometry}
                  material={nodes.Cylinder176_White_metal_d1_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder174_White_metal_d1_0.geometry}
                material={nodes.Cylinder174_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder174_White_metal_d2_0.geometry}
                material={nodes.Cylinder174_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <group position={[-0.31, 0, 0.58]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder190_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder190_Dark_metal_d1_0.material}
                />
              </group>
              <group
                position={[-0.15, 0.27, 0.58]}
                rotation={[0, 0, -0.69]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder191_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder191_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, 0.27, 0.58]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder192_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder192_Dark_metal_d1_0.material}
                />
              </group>
              <group
                position={[0.31, 0, 0.58]}
                rotation={[0, 0, 2.48]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder193_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder193_Dark_metal_d1_0.material}
                />
              </group>
              <group
                position={[-0.15, -0.27, 0.58]}
                rotation={[0, 0, -0.13]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder194_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder194_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, -0.27, 0.58]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder195_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder195_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.31, 0, 0.59]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder208_Dark_metal_0.geometry}
                  material={nodes.Cylinder208_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, 0.59]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder209_Dark_metal_0.geometry}
                  material={nodes.Cylinder209_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, 0.27, 0.59]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder210_Dark_metal_0.geometry}
                  material={nodes.Cylinder210_Dark_metal_0.material}
                />
              </group>
              <group position={[0.31, 0, 0.59]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder211_Dark_metal_0.geometry}
                  material={nodes.Cylinder211_Dark_metal_0.material}
                />
              </group>
              <group
                position={[-0.15, -0.27, 0.59]}
                rotation={[0, 0, -0.13]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder212_Dark_metal_0.geometry}
                  material={nodes.Cylinder212_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, -0.27, 0.59]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder213_Dark_metal_0.geometry}
                  material={nodes.Cylinder213_Dark_metal_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder175_Dark_metal_0.geometry}
                material={nodes.Cylinder175_Dark_metal_0.material}
              />
            </group>
            <group
              position={[-0.94, -0.01, 0.4]}
              rotation={[0.05, -1.33, -3]}
              scale={[1, 1, 1]}
            >
              <mesh
                geometry={nodes.Cylinder185_Dark_metal_0.geometry}
                material={nodes.Cylinder185_Dark_metal_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder122_Tire_d1_0.geometry}
              material={nodes.Cylinder122_Tire_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder122_Tire_0.geometry}
              material={nodes.Cylinder122_Tire_0.material}
            />
          </group>
          <group
            position={[0, 94.87, -19.7]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder123_White_metal_d2_0.geometry}
              material={nodes.Cylinder123_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[0, 94.87, -237.71]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder124_White_metal_d2_0.geometry}
              material={nodes.Cylinder124_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[153.15, 94.87, 400.02]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder126_White_metal_d2_0.geometry}
              material={nodes.Cylinder126_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[141.39, 433.81, -98.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[0, 0, 0.15]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder143_White_metal_d2_0.geometry}
                material={nodes.Cylinder143_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, -0.37]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder144_White_metal_d2_0.geometry}
                material={nodes.Cylinder144_White_metal_d2_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder129_White_metal_d2_0.geometry}
              material={nodes.Cylinder129_White_metal_d2_0.material}
            />
            <mesh
              geometry={nodes.Cylinder129_Or_metal_s1d_0.geometry}
              material={nodes.Cylinder129_Or_metal_s1d_0.material}
            />
            <mesh
              geometry={nodes.Cylinder129_White_metal_d1_0.geometry}
              material={nodes.Cylinder129_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[0, 188.84, 135.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[1.66, 0, 0.14]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cube043_White_metal_l1_0.geometry}
                material={nodes.Cube043_White_metal_l1_0.material}
              />
              <mesh
                geometry={nodes.Cube043_White_metal_d2_0.geometry}
                material={nodes.Cube043_White_metal_d2_0.material}
              />
            </group>
            <group
              position={[1.53, -0.59, 0.57]}
              rotation={[0, Math.PI / 2, 0]}
            >
              <group
                position={[-0.08, -0.11, -0.01]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  geometry={nodes.Roundcube007_Blue_emiss_0.geometry}
                  material={nodes.Roundcube007_Blue_emiss_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cube054_White_metal_d1_0.geometry}
                material={nodes.Cube054_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cube054_White_metal_d2_0.geometry}
                material={nodes.Cube054_White_metal_d2_0.material}
              />
            </group>
            <group
              position={[1.46, -0.49, 0.08]}
              rotation={[0, Math.PI / 2, 0]}
            >
              <group
                position={[-0.12, -0.03, 0.11]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  geometry={nodes.Roundcube008_Dark_metal_0.geometry}
                  material={nodes.Roundcube008_Dark_metal_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cube055_White_metal_d1_0.geometry}
                material={nodes.Cube055_White_metal_d1_0.material}
              />
            </group>
            <group
              position={[1.4, -0.51, -0.28]}
              rotation={[0, Math.PI / 2, 0]}
            >
              <group
                position={[-0.06, -0.01, 0.18]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  geometry={nodes.Roundcube009_Dark_metal_0.geometry}
                  material={nodes.Roundcube009_Dark_metal_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cube056_White_metal_d1_0.geometry}
                material={nodes.Cube056_White_metal_d1_0.material}
              />
            </group>
            <group position={[1.48, 0, -0.83]} rotation={[0, 0, Math.PI / 2]}>
              <mesh
                geometry={nodes.Cube057_White_metal_d2_0.geometry}
                material={nodes.Cube057_White_metal_d2_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cube039_White_metal_0.geometry}
              material={nodes.Cube039_White_metal_0.material}
            />
          </group>
          <group
            position={[0, 381.56, -180.98]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube040_Gray_metal_0.geometry}
              material={nodes.Cube040_Gray_metal_0.material}
            />
          </group>
          <group
            position={[0, 287.72, -305.4]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube041_White_metal_d1_0.geometry}
              material={nodes.Cube041_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[166.24, 94.87, -19.7]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder132_White_metal_d2_0.geometry}
              material={nodes.Cylinder132_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[166.24, 94.87, -237.71]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder133_White_metal_d2_0.geometry}
              material={nodes.Cylinder133_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[0, 370.87, -98.13]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder134_Or_metal_s1d_0.geometry}
              material={nodes.Cylinder134_Or_metal_s1d_0.material}
            />
          </group>
          <group
            position={[0, 370.87, -196.86]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder135_Or_metal_s1d_0.geometry}
              material={nodes.Cylinder135_Or_metal_s1d_0.material}
            />
          </group>
          <group
            position={[0, 358.04, 63.79]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube042_Gray_metal_0.geometry}
              material={nodes.Cube042_Gray_metal_0.material}
            />
            <mesh
              geometry={nodes.Cube042_Gray_metal_d1_0.geometry}
              material={nodes.Cube042_Gray_metal_d1_0.material}
            />
          </group>
          <group
            position={[62.66, 375.1, 127.99]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder136__0.geometry}
              material={materials["Cylinder.136__0"]}
            />
          </group>
          <group
            position={[142.83, 94.87, -19.7]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder137_White_metal_d1_0.geometry}
              material={nodes.Cylinder137_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder137_White_metal_d2_0.geometry}
              material={nodes.Cylinder137_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[86.37, 116.46, -19.7]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder138_White_metal_d2_0.geometry}
              material={nodes.Cylinder138_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[86.37, 116.46, -237.71]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder139_White_metal_d2_0.geometry}
              material={nodes.Cylinder139_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[141.39, 410.78, -98.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder141_Or_metal_s1d_0.geometry}
              material={nodes.Cylinder141_Or_metal_s1d_0.material}
            />
          </group>
          <group
            position={[141.39, 410.78, -196.86]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder142_Or_metal_s1d_0.geometry}
              material={nodes.Cylinder142_Or_metal_s1d_0.material}
            />
          </group>
          <group
            position={[141.39, 395.13, -196.86]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder146_Tire_0.geometry}
              material={nodes.Cylinder146_Tire_0.material}
            />
          </group>
          <group
            position={[141.39, 399.05, -196.86]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder147_Gray_metal_0.geometry}
              material={nodes.Cylinder147_Gray_metal_0.material}
            />
          </group>
          <group
            position={[141.39, 403.78, -196.86]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder148_Gray_metal_0.geometry}
              material={nodes.Cylinder148_Gray_metal_0.material}
            />
          </group>
          <group
            position={[-33.17, 236.96, 28.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube044_Brown_metal_0.geometry}
              material={nodes.Cube044_Brown_metal_0.material}
            />
          </group>
          <group
            position={[70.33, 389.34, -36.15]}
            rotation={[0, 0.32, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder149_Gray_metal_0.geometry}
              material={nodes.Cylinder149_Gray_metal_0.material}
            />
          </group>
          <group
            position={[72.47, 373.46, 68.28]}
            rotation={[0, -0.06, -0.51]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder150_Gray_metal_0.geometry}
              material={nodes.Cylinder150_Gray_metal_0.material}
            />
          </group>
          <group
            position={[49.28, 389.26, -50.69]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder151_Gray_metal_0.geometry}
              material={nodes.Cylinder151_Gray_metal_0.material}
            />
          </group>
          <group
            position={[49.28, 372.13, 89.83]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder152_Gray_metal_0.geometry}
              material={nodes.Cylinder152_Gray_metal_0.material}
            />
          </group>
          <group
            position={[69.8, 390.31, -196.86]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder153_White_metal_d2_0.geometry}
              material={nodes.Cylinder153_White_metal_d2_0.material}
            />
            <mesh
              geometry={nodes.Cylinder153_White_metal_d1_0.geometry}
              material={nodes.Cylinder153_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder153_Or_metal_s1d_0.geometry}
              material={nodes.Cylinder153_Or_metal_s1d_0.material}
            />
          </group>
          <group
            position={[69.8, 390.31, -98.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder154_White_metal_d2_0.geometry}
              material={nodes.Cylinder154_White_metal_d2_0.material}
            />
            <mesh
              geometry={nodes.Cylinder154_White_metal_d1_0.geometry}
              material={nodes.Cylinder154_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder154_Or_metal_s1d_0.geometry}
              material={nodes.Cylinder154_Or_metal_s1d_0.material}
            />
          </group>
          <group
            position={[141.29, 284.03, -98.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder128_White_metal_0.geometry}
                material={nodes.Cylinder128_White_metal_0.material}
              />
              <mesh
                geometry={nodes.Cylinder128_Or_metal_s1d_0.geometry}
                material={nodes.Cylinder128_Or_metal_s1d_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder145_Or_metal_s1d_0.geometry}
                material={nodes.Cylinder145_Or_metal_s1d_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder156_White_metal_0.geometry}
                material={nodes.Cylinder156_White_metal_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder157_Or_metal_d2_0.geometry}
                material={nodes.Cylinder157_Or_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0.99, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder162_Or_metal_d2_0.geometry}
                material={nodes.Cylinder162_Or_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0.1]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder188_Tire_0.geometry}
                material={nodes.Cylinder188_Tire_0.material}
              />
            </group>
            <group position={[0, 0.99, 0.1]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder189_Tire_0.geometry}
                material={nodes.Cylinder189_Tire_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder155_Or_metal_d2_0.geometry}
              material={nodes.Cylinder155_Or_metal_d2_0.material}
            />
          </group>
          <group
            position={[141.29, 284.03, -196.86]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder158_White_metal_0.geometry}
                material={nodes.Cylinder158_White_metal_0.material}
              />
              <mesh
                geometry={nodes.Cylinder158_Or_metal_s1d_0.geometry}
                material={nodes.Cylinder158_Or_metal_s1d_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder159_Or_metal_s1d_0.geometry}
                material={nodes.Cylinder159_Or_metal_s1d_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder161_White_metal_0.geometry}
                material={nodes.Cylinder161_White_metal_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder160_Or_metal_d2_0.geometry}
              material={nodes.Cylinder160_Or_metal_d2_0.material}
            />
          </group>
          <group
            position={[140.72, 300.44, -39.56]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group
              position={[0, 0, 0.01]}
              rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Cube060_White_metal_d2_0.geometry}
                material={nodes.Cube060_White_metal_d2_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder163_White_metal_d1_0.geometry}
              material={nodes.Cylinder163_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder163_White_metal_0.geometry}
              material={nodes.Cylinder163_White_metal_0.material}
            />
          </group>
          <group
            position={[140.72, 269.94, -39.56]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group
              position={[0, 0, 0.01]}
              rotation={[-Math.PI / 2, -1.22, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Cube061_White_metal_d2_0.geometry}
                material={nodes.Cube061_White_metal_d2_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder164_White_metal_d1_0.geometry}
              material={nodes.Cylinder164_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder164_White_metal_0.geometry}
              material={nodes.Cylinder164_White_metal_0.material}
            />
          </group>
          <group
            position={[118.3, 151.19, -80.92]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group
              position={[-0.86, -0.8, -1.18]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <mesh
                geometry={nodes.Cube046_Brown_metal_0.geometry}
                material={nodes.Cube046_Brown_metal_0.material}
              />
            </group>
            <group
              position={[-0.09, 0.14, 0.04]}
              rotation={[-Math.PI / 2, -0.58, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Cylinder168_Tire_d1_0.geometry}
                material={nodes.Cylinder168_Tire_d1_0.material}
              />
            </group>
            <group
              position={[-0.03, 0.17, -2.4]}
              rotation={[-Math.PI / 2, -0.34, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Cylinder172_Tire_d1_0.geometry}
                material={nodes.Cylinder172_Tire_d1_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder165_Tire_0.geometry}
              material={nodes.Cylinder165_Tire_0.material}
            />
            <mesh
              geometry={nodes.Cylinder165_Tire_d1_0.geometry}
              material={nodes.Cylinder165_Tire_d1_0.material}
            />
          </group>
          <group
            position={[118.3, 151.19, -144.18]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group
              position={[-0.7, -1.31, -1.18]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <mesh
                geometry={nodes.Cube047_Brown_metal_0.geometry}
                material={nodes.Cube047_Brown_metal_0.material}
              />
            </group>
            <group
              position={[-0.8, -1.31, -1.18]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <mesh
                geometry={nodes.Cube048_Brown_metal_0.geometry}
                material={nodes.Cube048_Brown_metal_0.material}
              />
            </group>
            <group
              position={[0.19, -0.94, 0.08]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <mesh
                geometry={nodes.Cylinder167_Tire_d1_0.geometry}
                material={nodes.Cylinder167_Tire_d1_0.material}
              />
            </group>
            <group
              position={[-0.11, -0.11, 0.05]}
              rotation={[Math.PI / 2, -0.74, Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Cylinder169_Tire_d1_0.geometry}
                material={nodes.Cylinder169_Tire_d1_0.material}
              />
            </group>
            <group
              position={[0.08, 0.14, 0.05]}
              rotation={[Math.PI / 2, -0.38, Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Cylinder170_Tire_d1_0.geometry}
                material={nodes.Cylinder170_Tire_d1_0.material}
              />
            </group>
            <group
              position={[-0.08, 0.14, -2.4]}
              rotation={[-Math.PI / 2, -0.51, -Math.PI / 2]}
              scale={[1, 1, 1]}
            >
              <mesh
                geometry={nodes.Cylinder171_Tire_d1_0.geometry}
                material={nodes.Cylinder171_Tire_d1_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder166_Tire_0.geometry}
              material={nodes.Cylinder166_Tire_0.material}
            />
            <mesh
              geometry={nodes.Cylinder166_Tire_d1_0.geometry}
              material={nodes.Cylinder166_Tire_d1_0.material}
            />
          </group>
          <group
            position={[97.7, 175.35, 332.01]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube049_White_metal_0.geometry}
              material={nodes.Cube049_White_metal_0.material}
            />
          </group>
          <group
            position={[59.85, 138.74, 332.9]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube050_White_metal_d1_0.geometry}
              material={nodes.Cube050_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cube050_White_metal_d2_0.geometry}
              material={nodes.Cube050_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[0, 147.69, 324.02]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube051_White_metal_d2_0.geometry}
              material={nodes.Cube051_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[74.76, 149.83, 324.02]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube052_White_metal_d1_0.geometry}
              material={nodes.Cube052_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[73.1, 375.91, 138.88]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube053_Gray_metal_d1_0.geometry}
              material={nodes.Cube053_Gray_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cube053_Gray_metal_d2_0.geometry}
              material={materials.Gray_metal_d2}
            />
          </group>
          <group
            position={[141.39, 399.05, -196.86]}
            rotation={[-Math.PI / 2, 0, 0.02]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Vert001_Dark_metal_0.geometry}
              material={nodes.Vert001_Dark_metal_0.material}
            />
          </group>
          <group
            position={[141.27, 605.64, -204.9]}
            rotation={[-1.73, 0, 0.02]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Roundcube005_Gray_metal_0.geometry}
              material={nodes.Roundcube005_Gray_metal_0.material}
            />
          </group>
          <group
            position={[65.11, 374.75, 149.65]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Roundcube006_Blue_emiss_0.geometry}
              material={nodes.Roundcube006_Blue_emiss_0.material}
            />
          </group>
          <group
            position={[36.9, 410.33, -232.73]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube058_White_metal_d1_0.geometry}
              material={nodes.Cube058_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[36.9, 384.2, 5.28]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube059_White_metal_d1_0.geometry}
              material={nodes.Cube059_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[148.92, 317.97, -276.6]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube063_White_metal_d2_0.geometry}
              material={nodes.Cube063_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[27.72, 349.29, 226.84]}
            rotation={[-1.36, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube064_Gray_metal_d1_0.geometry}
              material={nodes.Cube064_Gray_metal_d1_0.material}
            />
          </group>
          <group
            position={[27.72, 349.29, 226.84]}
            rotation={[-1.36, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube065_Gray_metal_0.geometry}
              material={nodes.Cube065_Gray_metal_0.material}
            />
          </group>
          <group
            position={[111.5, 194.3, 365.26]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder226_White_metal_d1_0.geometry}
              material={nodes.Cylinder226_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[109.35, 207.78, 348.91]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder227_White_metal_d1_0.geometry}
              material={nodes.Cylinder227_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[109.35, 187.88, 346.78]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder228_White_metal_d1_0.geometry}
              material={nodes.Cylinder228_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[85.66, 195.37, 371.24]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder229_White_metal_d1_0.geometry}
              material={nodes.Cylinder229_White_metal_d1_0.material}
            />
          </group>
          <group
            position={[0, 236.96, 28.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube045_Gray_metal_0.geometry}
              material={nodes.Cube045_Gray_metal_0.material}
            />
            <mesh
              geometry={nodes.Cube045_Glass_0.geometry}
              material={materials.Glass}
            />
            <mesh
              geometry={nodes.Cube045_Or_metal_0.geometry}
              material={nodes.Cube045_Or_metal_0.material}
            />
            <mesh
              geometry={nodes.Cube045_White_metal_0.geometry}
              material={nodes.Cube045_White_metal_0.material}
            />
            <mesh
              geometry={nodes.Cube045_Or_metal_d1_0.geometry}
              material={materials.Or_metal_d1}
            />
            <mesh
              geometry={nodes.Cube045_White_metal_d2_0.geometry}
              material={nodes.Cube045_White_metal_d2_0.material}
            />
            <mesh
              geometry={nodes.Cube045_Or_metal_d2_0.geometry}
              material={nodes.Cube045_Or_metal_d2_0.material}
            />
          </group>
          <group
            position={[224.41, 94.87, -19.7]}
            rotation={[-0.23, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[0, 0, 0.16]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder131_White_metal_d1_0.geometry}
                material={nodes.Cylinder131_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder131_White_metal_d2_0.geometry}
                material={nodes.Cylinder131_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <group
                position={[0, 0, 0]}
                rotation={[0, 0, -0.16]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder179_White_metal_d2_0.geometry}
                  material={nodes.Cylinder179_White_metal_d2_0.material}
                />
                <mesh
                  geometry={nodes.Cylinder179_White_metal_d1_0.geometry}
                  material={nodes.Cylinder179_White_metal_d1_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder177_White_metal_d1_0.geometry}
                material={nodes.Cylinder177_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder177_White_metal_d2_0.geometry}
                material={nodes.Cylinder177_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <group position={[-0.31, 0, 0.58]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder181_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder181_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, 0.58]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder182_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder182_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, 0.27, 0.58]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder183_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder183_Dark_metal_d1_0.material}
                />
              </group>
              <group
                position={[0.31, 0, 0.58]}
                rotation={[0, 0, 2.48]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder184_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder184_Dark_metal_d1_0.material}
                />
              </group>
              <group
                position={[-0.15, -0.27, 0.58]}
                rotation={[0, 0, -0.13]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder186_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder186_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, -0.27, 0.58]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder187_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder187_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.31, 0, 0.59]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder196_Dark_metal_0.geometry}
                  material={nodes.Cylinder196_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, 0.59]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder197_Dark_metal_0.geometry}
                  material={nodes.Cylinder197_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, 0.27, 0.59]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder198_Dark_metal_0.geometry}
                  material={nodes.Cylinder198_Dark_metal_0.material}
                />
              </group>
              <group position={[0.31, 0, 0.59]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder199_Dark_metal_0.geometry}
                  material={nodes.Cylinder199_Dark_metal_0.material}
                />
              </group>
              <group
                position={[-0.15, -0.27, 0.59]}
                rotation={[0, 0, -0.13]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder200_Dark_metal_0.geometry}
                  material={nodes.Cylinder200_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, -0.27, 0.59]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder201_Dark_metal_0.geometry}
                  material={nodes.Cylinder201_Dark_metal_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder178_Dark_metal_0.geometry}
                material={nodes.Cylinder178_Dark_metal_0.material}
              />
            </group>
            <group
              position={[-0.94, -0.01, 0.4]}
              rotation={[0.05, -1.33, -3]}
              scale={[1, 1, 1]}
            >
              <mesh
                geometry={nodes.Cylinder180_Dark_metal_0.geometry}
                material={nodes.Cylinder180_Dark_metal_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder130_Tire_d1_0.geometry}
              material={nodes.Cylinder130_Tire_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder130_Tire_0.geometry}
              material={nodes.Cylinder130_Tire_0.material}
            />
          </group>
          <group
            position={[224.41, 94.87, -237.71]}
            rotation={[-2.93, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[0, 0, 0.16]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder203_White_metal_d1_0.geometry}
                material={nodes.Cylinder203_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder203_White_metal_d2_0.geometry}
                material={nodes.Cylinder203_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <group position={[0, 0, 0]} rotation={[0, 0, -0.16]}>
                <mesh
                  geometry={nodes.Cylinder206_White_metal_d2_0.geometry}
                  material={nodes.Cylinder206_White_metal_d2_0.material}
                />
                <mesh
                  geometry={nodes.Cylinder206_White_metal_d1_0.geometry}
                  material={nodes.Cylinder206_White_metal_d1_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder204_White_metal_d1_0.geometry}
                material={nodes.Cylinder204_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder204_White_metal_d2_0.geometry}
                material={nodes.Cylinder204_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <group position={[-0.31, 0, 0.58]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder214_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder214_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, 0.58]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder215_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder215_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, 0.27, 0.58]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder216_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder216_Dark_metal_d1_0.material}
                />
              </group>
              <group
                position={[0.31, 0, 0.58]}
                rotation={[0, 0, 2.48]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder217_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder217_Dark_metal_d1_0.material}
                />
              </group>
              <group
                position={[-0.15, -0.27, 0.58]}
                rotation={[0, 0, -0.13]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder218_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder218_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, -0.27, 0.58]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder219_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder219_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.31, 0, 0.59]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder220_Dark_metal_0.geometry}
                  material={nodes.Cylinder220_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, 0.59]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder221_Dark_metal_0.geometry}
                  material={nodes.Cylinder221_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, 0.27, 0.59]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder222_Dark_metal_0.geometry}
                  material={nodes.Cylinder222_Dark_metal_0.material}
                />
              </group>
              <group position={[0.31, 0, 0.59]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder223_Dark_metal_0.geometry}
                  material={nodes.Cylinder223_Dark_metal_0.material}
                />
              </group>
              <group
                position={[-0.15, -0.27, 0.59]}
                rotation={[0, 0, -0.13]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder224_Dark_metal_0.geometry}
                  material={nodes.Cylinder224_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, -0.27, 0.59]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder225_Dark_metal_0.geometry}
                  material={nodes.Cylinder225_Dark_metal_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder205_Dark_metal_0.geometry}
                material={nodes.Cylinder205_Dark_metal_0.material}
              />
            </group>
            <group
              position={[-0.94, -0.01, 0.4]}
              rotation={[0.05, -1.33, -3]}
              scale={[1, 1, 1]}
            >
              <mesh
                geometry={nodes.Cylinder207_Dark_metal_0.geometry}
                material={nodes.Cylinder207_Dark_metal_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder202_Tire_d1_0.geometry}
              material={nodes.Cylinder202_Tire_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder202_Tire_0.geometry}
              material={nodes.Cylinder202_Tire_0.material}
            />
          </group>
          <group
            position={[-224.41, 94.87, 400.02]}
            rotation={[-0.77, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[0, 0, -0.16]} rotation={[0, 0, Math.PI]}>
              <mesh
                geometry={nodes.Cylinder231_White_metal_d1_0.geometry}
                material={nodes.Cylinder231_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder231_White_metal_d2_0.geometry}
                material={nodes.Cylinder231_White_metal_d2_0.material}
              />
            </group>
            <group rotation={[0, 0, Math.PI]}>
              <group position={[0, 0, 0]} rotation={[0, 0, -0.16]}>
                <mesh
                  geometry={nodes.Cylinder234_White_metal_d2_0.geometry}
                  material={nodes.Cylinder234_White_metal_d2_0.material}
                />
                <mesh
                  geometry={nodes.Cylinder234_White_metal_d1_0.geometry}
                  material={nodes.Cylinder234_White_metal_d1_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder232_White_metal_d1_0.geometry}
                material={nodes.Cylinder232_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder232_White_metal_d2_0.geometry}
                material={nodes.Cylinder232_White_metal_d2_0.material}
              />
            </group>
            <group rotation={[0, 0, Math.PI]}>
              <group position={[0.31, 0, -0.58]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder236_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder236_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, -0.27, -0.58]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder237_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder237_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.15, -0.27, -0.58]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder238_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder238_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.31, 0, -0.58]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder239_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder239_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, 0.27, -0.58]} rotation={[0, 0, -0.13]}>
                <mesh
                  geometry={nodes.Cylinder240_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder240_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, -0.58]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder241_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder241_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.31, 0, -0.59]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder242_Dark_metal_0.geometry}
                  material={nodes.Cylinder242_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, -0.27, -0.59]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder243_Dark_metal_0.geometry}
                  material={nodes.Cylinder243_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.15, -0.27, -0.59]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder244_Dark_metal_0.geometry}
                  material={nodes.Cylinder244_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.31, 0, -0.59]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder245_Dark_metal_0.geometry}
                  material={nodes.Cylinder245_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, 0.27, -0.59]} rotation={[0, 0, -0.13]}>
                <mesh
                  geometry={nodes.Cylinder246_Dark_metal_0.geometry}
                  material={nodes.Cylinder246_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, -0.59]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder247_Dark_metal_0.geometry}
                  material={nodes.Cylinder247_Dark_metal_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder233_Dark_metal_0.geometry}
                material={nodes.Cylinder233_Dark_metal_0.material}
              />
            </group>
            <group
              position={[-0.94, -0.01, -0.4]}
              rotation={[-0.05, 1.33, 0.14]}
            >
              <mesh
                geometry={nodes.Cylinder235_Dark_metal_0.geometry}
                material={nodes.Cylinder235_Dark_metal_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder230_Tire_d1_0.geometry}
              material={nodes.Cylinder230_Tire_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder230_Tire_0.geometry}
              material={nodes.Cylinder230_Tire_0.material}
            />
          </group>
          <group
            position={[-224.41, 94.87, -19.7]}
            rotation={[-2.65, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[0, 0, -0.16]} rotation={[0, 0, Math.PI]}>
              <mesh
                geometry={nodes.Cylinder249_White_metal_d1_0.geometry}
                material={nodes.Cylinder249_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder249_White_metal_d2_0.geometry}
                material={nodes.Cylinder249_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, Math.PI]}>
              <group position={[0, 0, 0]} rotation={[0, 0, -0.16]}>
                <mesh
                  geometry={nodes.Cylinder252_White_metal_d2_0.geometry}
                  material={nodes.Cylinder252_White_metal_d2_0.material}
                />
                <mesh
                  geometry={nodes.Cylinder252_White_metal_d1_0.geometry}
                  material={nodes.Cylinder252_White_metal_d1_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder250_White_metal_d1_0.geometry}
                material={nodes.Cylinder250_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder250_White_metal_d2_0.geometry}
                material={nodes.Cylinder250_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, Math.PI]}>
              <group position={[0.31, 0, -0.58]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder254_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder254_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, -0.27, -0.58]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder255_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder255_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.15, -0.27, -0.58]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder256_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder256_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.31, 0, -0.58]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder257_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder257_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, 0.27, -0.58]} rotation={[0, 0, -0.13]}>
                <mesh
                  geometry={nodes.Cylinder258_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder258_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, -0.58]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder259_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder259_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.31, 0, -0.59]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder260_Dark_metal_0.geometry}
                  material={nodes.Cylinder260_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, -0.27, -0.59]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder261_Dark_metal_0.geometry}
                  material={nodes.Cylinder261_Dark_metal_0.material}
                />
              </group>
              <group
                position={[-0.15, -0.27, -0.59]}
                rotation={[0, 0, -0.77]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder262_Dark_metal_0.geometry}
                  material={nodes.Cylinder262_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.31, 0, -0.59]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder263_Dark_metal_0.geometry}
                  material={nodes.Cylinder263_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, 0.27, -0.59]} rotation={[0, 0, -0.13]}>
                <mesh
                  geometry={nodes.Cylinder264_Dark_metal_0.geometry}
                  material={nodes.Cylinder264_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, -0.59]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder265_Dark_metal_0.geometry}
                  material={nodes.Cylinder265_Dark_metal_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder251_Dark_metal_0.geometry}
                material={nodes.Cylinder251_Dark_metal_0.material}
              />
            </group>
            <group
              position={[-0.94, -0.01, -0.4]}
              rotation={[-0.05, 1.33, 0.14]}
              scale={[1, 1, 1]}
            >
              <mesh
                geometry={nodes.Cylinder253_Dark_metal_0.geometry}
                material={nodes.Cylinder253_Dark_metal_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder248_Tire_d1_0.geometry}
              material={nodes.Cylinder248_Tire_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder248_Tire_0.geometry}
              material={nodes.Cylinder248_Tire_0.material}
            />
          </group>
          <group
            position={[-224.41, 94.87, -237.71]}
            rotation={[0.92, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <group position={[0, 0, -0.16]} rotation={[0, 0, Math.PI]}>
              <mesh
                geometry={nodes.Cylinder267_White_metal_d1_0.geometry}
                material={nodes.Cylinder267_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder267_White_metal_d2_0.geometry}
                material={nodes.Cylinder267_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, Math.PI]}>
              <group position={[0, 0, 0]} rotation={[0, 0, -0.16]}>
                <mesh
                  geometry={nodes.Cylinder270_White_metal_d2_0.geometry}
                  material={nodes.Cylinder270_White_metal_d2_0.material}
                />
                <mesh
                  geometry={nodes.Cylinder270_White_metal_d1_0.geometry}
                  material={nodes.Cylinder270_White_metal_d1_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder268_White_metal_d1_0.geometry}
                material={nodes.Cylinder268_White_metal_d1_0.material}
              />
              <mesh
                geometry={nodes.Cylinder268_White_metal_d2_0.geometry}
                material={nodes.Cylinder268_White_metal_d2_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[0, 0, Math.PI]}>
              <group position={[0.31, 0, -0.58]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder272_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder272_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, -0.27, -0.58]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder273_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder273_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.15, -0.27, -0.58]} rotation={[0, 0, -0.77]}>
                <mesh
                  geometry={nodes.Cylinder274_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder274_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.31, 0, -0.58]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder275_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder275_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.15, 0.27, -0.58]} rotation={[0, 0, -0.13]}>
                <mesh
                  geometry={nodes.Cylinder276_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder276_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, -0.58]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder277_Dark_metal_d1_0.geometry}
                  material={nodes.Cylinder277_Dark_metal_d1_0.material}
                />
              </group>
              <group position={[0.31, 0, -0.59]} rotation={[0, 0, -0.17]}>
                <mesh
                  geometry={nodes.Cylinder278_Dark_metal_0.geometry}
                  material={nodes.Cylinder278_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, -0.27, -0.59]} rotation={[0, 0, -0.69]}>
                <mesh
                  geometry={nodes.Cylinder279_Dark_metal_0.geometry}
                  material={nodes.Cylinder279_Dark_metal_0.material}
                />
              </group>
              <group
                position={[-0.15, -0.27, -0.59]}
                rotation={[0, 0, -0.77]}
                scale={[1, 1, 1]}
              >
                <mesh
                  geometry={nodes.Cylinder280_Dark_metal_0.geometry}
                  material={nodes.Cylinder280_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.31, 0, -0.59]} rotation={[0, 0, 2.48]}>
                <mesh
                  geometry={nodes.Cylinder281_Dark_metal_0.geometry}
                  material={nodes.Cylinder281_Dark_metal_0.material}
                />
              </group>
              <group position={[0.15, 0.27, -0.59]} rotation={[0, 0, -0.13]}>
                <mesh
                  geometry={nodes.Cylinder282_Dark_metal_0.geometry}
                  material={nodes.Cylinder282_Dark_metal_0.material}
                />
              </group>
              <group position={[-0.15, 0.27, -0.59]} rotation={[0, 0, 2.49]}>
                <mesh
                  geometry={nodes.Cylinder283_Dark_metal_0.geometry}
                  material={nodes.Cylinder283_Dark_metal_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder269_Dark_metal_0.geometry}
                material={nodes.Cylinder269_Dark_metal_0.material}
              />
            </group>
            <group
              position={[-0.94, -0.01, -0.4]}
              rotation={[-0.05, 1.33, 0.14]}
            >
              <mesh
                geometry={nodes.Cylinder271_Dark_metal_0.geometry}
                material={nodes.Cylinder271_Dark_metal_0.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder266_Tire_d1_0.geometry}
              material={nodes.Cylinder266_Tire_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder266_Tire_0.geometry}
              material={nodes.Cylinder266_Tire_0.material}
            />
          </group>
          <group
            position={[-141.39, 399.05, -196.86]}
            rotation={[-Math.PI / 2, 0, -0.4]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Vert002_Dark_metal_0.geometry}
              material={nodes.Vert002_Dark_metal_0.material}
            />
          </group>
          <group
            position={[122.46, 605.64, -94.82]}
            rotation={[-1.71, 0.06, -0.39]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Roundcube010_Gray_metal_0.geometry}
              material={nodes.Roundcube010_Gray_metal_0.material}
            />
          </group>
          <group
            position={[129.24, 217.18, 67.7]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube038_White_metal_0.geometry}
              material={nodes.Cube038_White_metal_0.material}
            />
            <mesh
              geometry={nodes.Cube038_White_metal_d1_0.geometry}
              material={nodes.Cube038_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cube038_Or_metal_0.geometry}
              material={nodes.Cube038_Or_metal_0.material}
            />
          </group>
          <group
            position={[163.65, 94.87, 277.28]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder286_White_metal_d2_0.geometry}
              material={nodes.Cylinder286_White_metal_d2_0.material}
            />
            <mesh
              geometry={nodes.Cylinder286_White_metal_d1_0.geometry}
              material={nodes.Cylinder286_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder286_White_metal_l1_0.geometry}
              material={nodes.Cylinder286_White_metal_l1_0.material}
            />
          </group>
          <group
            position={[0, 94.87, 277.28]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[20.02, 20.02, 135.21]}
          >
            <mesh
              geometry={nodes.Cylinder125_White_metal_d2_0.geometry}
              material={nodes.Cylinder125_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[142.83, 94.87, 400.02]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Cylinder127_White_metal_d1_0.geometry}
              material={nodes.Cylinder127_White_metal_d1_0.material}
            />
            <mesh
              geometry={nodes.Cylinder127_White_metal_d2_0.geometry}
              material={nodes.Cylinder127_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[86.37, 116.46, 277.28]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[12.64, 12.64, 11.99]}
          >
            <mesh
              geometry={nodes.Cylinder140_White_metal_d2_0.geometry}
              material={nodes.Cylinder140_White_metal_d2_0.material}
            />
          </group>
          <group
            position={[691.05, 393.19, 782.7]}
            rotation={[0, 0, 0]}
            scale={[100, 100, 100]}
          >
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group
            position={[-1694.6, 393.19, 946.1]}
            rotation={[0, 0, 0]}
            scale={[100, 100, 100]}
          >
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group
            position={[-919.37, 393.19, -611.96]}
            rotation={[0, 0, 0]}
            scale={[100, 100, 100]}
          >
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group
            position={[26.87, 1613.04, -611.96]}
            rotation={[0, 0, 0]}
            scale={[100, 100, 100]}
          >
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group
            position={[1167.27, 842.62, 1885.78]}
            rotation={[-Math.PI, 1.01, 2.86]}
            scale={[100, 100, 100]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/rover.gltf");
