/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");

  useFrame(({ mouse }) => {
    group.current.rotation.y += 0.005;
    group.current.position.x = mouse.x * 1.5;
    group.current.position.y = -mouse.y * 1.5;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, -1]} rotation={[0.24, -0.5, 0.56]} scale={5.5}>
          <mesh
            geometry={nodes.planet001_1.geometry}
            material={nodes.planet001_1.material}
          />

          <mesh
            geometry={nodes.planet001_2.geometry}
            material={nodes.planet001_2.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
